Algoritmo "Acesso ao Sistema"
//Leia usuário e senha. Se usuário for 'admin' e senha for '1234', mostrar 'Acesso permitido'. Caso contrário, 'Acesso negado'.
Var
N1:caractere
N2:inteiro


Inicio
Escreva ("Qual o nome do usuario? ")
leia (N1)
Escreva ("Qual a senha do ususario? ")
Leia (N2)
se (N1 = "Admin") e (N2 = 1234 ) entao
escreva ("Acesso permitido.")
senao
escreva ("Acesso negado.")
fimse
Fimalgoritmo