Algoritmo "Classificação por Idade"
// Leia a idade de uma pessoa e classifique: Criança (0 a 12), Adolescente (13 a 17), Adulto (18 a 59), Idoso (60 ou mais).
Var
Idade: inteiro
Inicio
Escreva ("Qual a sua idade? ")
leia (Idade)
se (Idade < 12) entao
escreva ("Sua classificação é Criança")
senao
se (Idade >13) e (Idade <17)ENTAO
escreva ("Sua classificação é Adolescente")
senao
se(Idade >18) e (Idade <59)ENTAO
escreva ("Você é um Adulto")
senao
se (Idade >60)ENTAO
escreva ("Você é um Idoso")
fimse
fimse
fimse
fimse
Fimalgoritmo