Algoritmo "Contador até Zero"
//Leia números enquanto forem diferentes de zero. Ao final, exiba a quantidade de números digitados e a soma total.
Var
N1:real
N2:real
N3:real
Inicio
N1 <- 1
enquanto (N1 <> 0 ) faça
escreva ("Qual o Numero?")
Leia (N1)
N2 <- (N2 + N1)
N3 <- (N3 + 1)
fimenquanto
Escreval ("A quantidade de soma feitas é: ",N3)
Escreva ("A soma total dos numeros é igual à: ",N2)


Fimalgoritmo