Algoritmo "Desconto em Compra"
//Leia o valor de uma compra. Se o valor for maior que 100, aplicar 10% de desconto. Mostrar valor final.Leia o valor de uma compra. Se o valor for maior que 100, aplicar 10% de desconto. Mostrar valor final.Leia o valor de uma compra. Se o valor for maior que 100, aplicar 10% de desconto. Mostrar valor final.
Var
valor: real
desconto: real
Inicio
escreva ("Qual o valor total da compra? ")
leia (valor)
desconto<- (valor*0.9)
se (valor > 99) então
escreva ("O seu valor teve desconto, e o valor com desconto é igual á: ",desconto)
senao
escreva("O seu valor é igual á ",valor)
fimse

Fimalgoritmo