Algoritmo "Média de Três Notas"
//Leia três notas reais e calcule a média aritmética.
Var
Nota1: inteiro
Nota2: inteiro
Nota3: inteiro
Media: Real
Inicio
escreva("Qual a sua primeira nota? ")
leia (Nota1)
escreva("Qual a sua segunda nota? ")
leia (Nota2)
escreva("Qual a sua ultima nota? ")
leia (Nota3)
Media <-(Nota1+Nota2+Nota3)/3
escreva("A media das suas notas é ",Media)


Fimalgoritmo