Algoritmo "Média de Vários Valores"
//Leia 5 números reais e calcule a média.
Var
N1:real
N2:real
N3:real
N4:real
N5:real
So:real
Me:real
Inicio
Escreva ("Qual o Numero 1? ")
Leia (N1)
Escreva ("Qual o Numero 2? ")
Leia (N2)
Escreva ("Qual o Numero 3? ")
Leia (N3)
Escreva ("Qual o Numero 4? ")
Leia (N4)
Escreva ("Qual o Numero 5? ")
Leia (N5)
So <- (N1+N2+N3+N4+N5)
Me <- (So/5)
Escreva ("A Media entre os numeros é Igual à ",Me)


Fimalgoritmo